# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sparky}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Campbell"]
  s.date = %q{2009-11-16}
  s.description = %q{Light it up sparky! Random text (lorem ipsum), numbers, and names that at least look real..}
  s.email = %q{jason@greatergood.cc}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/sparky.rb",
     "lib/sparky.rb",
     "lib/sparky/lorem.rb",
     "lib/sparky/lorem.rb",
     "lib/sparky/name.rb",
     "lib/sparky/name.rb",
     "lib/sparky/names/first_names.rb",
     "lib/sparky/names/first_names.rb",
     "lib/sparky/names/last_names.rb",
     "lib/sparky/names/last_names.rb",
     "lib/sparky/sparky.rb",
     "lib/sparky/sparky.rb"
  ]
  s.homepage = %q{http://github.com/jxson/sparky}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{What do you call a dog with no back legs and metal nuts?}
  s.test_files = [
    "spec/sparky/lorem_spec.rb",
     "spec/sparky/sparky_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

